export const REQ_SUCCESS = "REQ_SUCCESS";
export const REQ = "REQ";
export const GET_ALL_EVENTS = "GET_ALL_EVENTS";
export const GET_ALL_PAST_EVENTS = "GET_ALL_PAST_EVENTS";
export const APPROVE_TICKET = "APPROVE_TICKET";
export const DISAPPROVE_TICKET = "DISAPPROVE_TICKET";
export const REQ_FAILURE = "REQ_FAILURE"