export const REQ_SUCCESS = "REQ_SUCCESS";
export const REQ = "REQ";
export const GET_PROFILE_DETAILS = "GET_PROFILE_DETAILS";
export const EDIT_PROFILE_DETAILS = "EDIT_PROFILE_DETAILS";
export const REQ_FAILURE = "REQ_FAILURE"